name: lint_and_test

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - '*'

jobs:
  lint_and_test:
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '20.11'

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
